# Generated by Django 4.2.3 on 2023-07-29 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_empresa', models.CharField(max_length=10, unique=True)),
                ('nombre_empresa', models.CharField(max_length=40)),
                ('direccion_empresa', models.CharField(max_length=60)),
                ('ciudad_empresa', models.CharField(max_length=30)),
                ('email_empresa', models.EmailField(max_length=40)),
                ('fono_empresa', models.CharField(max_length=12)),
                ('rubro_empresa', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='registroClientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=40)),
                ('password', models.CharField(max_length=8)),
                ('creacion', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
